version: '3.4'

services:

  admin-makiposiot:
    image: makipos/admin-smarthome:${ADMIN_SMARTHOME_VERSION}
    container_name: makiposiot-admin-smarthome-server
    restart: always
    networks:
      - makiposiot-frontend
    expose:
      - "80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_ADDR=http://localhost:3028
      - REACT_APP_MQTT_SERVER_ADDR=ws://localhost:8083/mqtt
      - REACT_APP_googleAnalyticsTrackerId=
    labels:
      - "traefik.port=80"
      - "traefik.root.frontend.rule=Host:localhost"
      - "traefik.frontend.entryPoints=httpfront"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400M
      labels:
        - "traefik.port=80"
        - "traefik.root.frontend.rule=Host:localhost"
        - "traefik.frontend.entryPoints=httpfront"


networks:
  makiposiot-frontend:
    external:
      name: makiposiot-frontend
