version: '3.4'

services:

  admin-makiposiot:
    image: makipos/admin-smarthome:${ADMIN_SMARTHOME_VERSION}
    container_name: makiposiot-admin-smarthome-server
    restart: always
    networks:
      - makiposiot-frontend
    expose:
      - "80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_ADDR=http://${SERVICE_DOMAIN}:3028
      - REACT_APP_SERVER_ADDR_HTTP=http://${SERVICE_DOMAIN}:3028
      - REACT_APP_MQTT_SERVER_ADDR=ws://${SERVICE_DOMAIN}:8083/mqtt
      - REACT_APP_googleAnalyticsTrackerId=
      - REACT_APP_googleClientId=
      - REACT_APP_facebookAppId=
    labels:
      - "traefik.port=80"
      - "traefik.root.frontend.rule=Host:${WEB_DOMAIN}"
      - "traefik.frontend.entryPoints=httpfront"

      - "traefik.http.services.admin.loadbalancer.server.port=80"
      - "traefik.http.routers.admin.entrypoints=httpfront,httpsfront"
      - "traefik.http.routers.admin.rule=Host(`${WEB_DOMAIN}`)"
      
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400M
      labels:
        - "traefik.port=80"
        - "traefik.root.frontend.rule=Host:${WEB_DOMAIN}"
        - "traefik.frontend.entryPoints=httpfront"

        - "traefik.http.services.admin.loadbalancer.server.port=80"
        - "traefik.http.routers.admin.entrypoints=httpfront,httpsfront"
        - "traefik.http.routers.admin.rule=Host(`${WEB_DOMAIN}`)"

networks:
  makiposiot-frontend:
    external:
      name: makiposiot-frontend
