version: '3.4'
services:

  traefik:
    image: traefik:1.7
    container_name: makiposiot-traefik-server
    command: --web --api --docker --docker.swarmmode
    restart: always
    sysctls:
      - net.core.somaxconn=32768
    networks:
      - vpc
    expose:
      - "80"
      - "8080"
    ports:
      - published: 3028
        target: 80
        protocol: tcp
        mode: host
      - published: 3029
        target: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/traefik:/etc/traefik
    deploy:
      placement:
        constraints:
          # - node.hostname == ${FRONT_NODE}
          - node.role == manager

networks:
  vpc:
    external:
      name: makiposiot-internal
