version: '3.4'

services:
  traefik-frontend:
    image: traefik:1.7
    container_name: makiposiot-traefik-frontend-server
    # command: --web --api --docker --docker.swarmmode
    restart: always
    sysctls:
      - net.core.somaxconn=32768
      # - net.core.netdev_max_backlog=16384
      # - net.core.rmem_default=262144
      # - net.core.wmem_default=262144
      # - net.core.rmem_max=16777216
      # - net.core.wmem_max=16777216
      # - net.core.optmem_max=16777216
      - net.ipv4.ip_local_port_range=1024 65000
      # - net.ipv4.tcp_rmem=1024 4096 16777216
      # - net.ipv4.tcp_wmem=1024 4096 16777216
      # - net.ipv4.tcp_max_syn_backlog=16384
      # - net.ipv4.tcp_max_tw_buckets=1048576
      # - net.ipv4.tcp_fin_timeout=30
      # - net.ipv4.tcp_keepalive_time=30
      # - net.ipv4.tcp_no_metrics_save=1
      # - net.ipv4.tcp_syn_retries=2
      # - net.ipv4.tcp_synack_retries=2
      # - net.ipv4.tcp_tw_recycle=1
      # - net.ipv4.tcp_tw_reuse=1
      # - net.nf_conntrack_max=1000000
      - net.netfilter.nf_conntrack_max=1000000
      - net.netfilter.nf_conntrack_tcp_timeout_time_wait=30
    expose:
      - "80"
      - "8080"
    networks:
      - makiposiot-frontend
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    volumes:
      - ${CONFIG_PATH}/traefik-frontend:/etc/traefik:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
          # - node.hostname == ${FRONT_NODE}
          - node.role == manager

  admin-makiposiot:
    image: makipos/admin-smarthome:${ADMIN_SMARTHOME_VERSION}
    container_name: makiposiot-admin-smarthome-server
    restart: always
    networks:
      - makiposiot-frontend
    expose:
      - "80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_ADDR=http://localhost:3028
      - REACT_APP_MQTT_SERVER_ADDR=ws://localhost:8083/mqtt
      - REACT_APP_googleAnalyticsTrackerId=
    # labels:
    #   - "traefik.port=80"
    #   - "traefik.root.frontend.rule=Host:vijalight-admin.ddns.net"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400M
      # labels:
      #   - "traefik.port=80"
      #   - "traefik.root.frontend.rule=Host:vijalight-admin.ddns.net"


networks:
  makiposiot-frontend:
    driver: overlay
    ipam:
     config:
       - subnet: 10.201.0.0/16
  # smarthome-frontend-back:
