/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: {
    'Kiến trúc': ['overview/architecture'],
    'Service': [
      'overview/service/database', 'overview/service/gateway',
      'overview/service/users_service', 'overview/service/devices_service',
      'overview/service/relations_service', 'overview/service/automatic_service',
      'overview/service/update_service', 'overview/service/webmanager'
    ],
    'Bảo mật': ['overview/security/network', 'overview/security/mqtt', 'overview/security/http']
  },
  'docs-tutorial': {
    'Cài đặt': ['tutorial/install/installation', 'tutorial/install/verify'],
    'Vận hành': [],
    'Kết nối': [
      {
        'type': 'category',
        'label': 'Cài đặt thiết bị IOT',
        'items': [
          'tutorial/connect/wificonfig'
        ]
      }
    ]
  }

};
